### ISSUE TITLE
两个 manifest 怎么编辑

### ISSUE THREAD

**Issue by xiaomizhou66** [Mrli2016/Chrome-extension-vue-template#1]
manifest.development.json	优化hot-reload.js的加载方式	前天
manifest.production.json	优化打包配置

**Comment by Mrli2016** [comment]
> manifest.development.json优化hot-reload.js的加载方式前天
> manifest.production.json优化打包配置

看需求的，目前来讲 除了开发环境需要在background加载hot-reload就行了，其他都一样。为了开发区分，如果是我的话两个manifest会用不同的插件名来区分。
