### ISSUE TITLE
halo

### ISSUE THREAD

**Issue by kongta** [Mrli2016/Chrome-extension-vue-template#2]
大佬 你好 如果我想在content里面用vue来渲染
一个列表应该如何操作？

**Comment by Mrli2016** [comment]
> 大佬你好如果我想在content里面用vue来渲染
> 一个列表应该如何操作？

可以先插入一个带有id值的div，然后用new Vue来渲染，但是我不建议这么做，操作dom还是用jQuery来比较好。我这边使用用webpack主要是为了开发打包方便，一味追求vue就太累了
